"use client";
import { useCallback, useEffect, useState } from "react";
import { AlertCircle, Check, Clock, ExternalLink, MapPin, Navigation, Pencil, Plus, RefreshCw, X } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import type { Observation } from "@/lib/intelligence";
import type { signalsSnapshot, ReportInput } from "@/lib/signals-store";
import type { Store } from "@/lib/types";

type Signals=Awaited<ReturnType<typeof signalsSnapshot>>;
const sourceNames={personal:"Eigener Vor-Ort-Fund",staff:"Mitarbeiterauskunft",community:"Community-Beitrag",secondhand:"Hinweis aus zweiter Hand"};
const kindNames={seen:"Ware gesehen",restock:"Verräumen beobachtet",empty:"Artikel nicht gefunden",announced:"Lieferung angekündigt"};
const date=(o:Observation)=>new Date(o.observed_at).toLocaleString("de-DE",{timeZone:"Europe/Berlin",day:"2-digit",month:"2-digit",year:"numeric",...(o.time_precision==="minute"?{hour:"2-digit",minute:"2-digit"}:{})});
const localInput=(n:number)=>{const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const clock=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
async function api(data?:unknown):Promise<Signals & {result?:{checked:number;imported:number}}> {
  const r=await fetch("/api/signals",data?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}:{cache:"no-store"});
  let j:Signals & {error?:string;result?:{checked:number;imported:number}};try{j=await r.json() as typeof j;}catch{throw new Error("Hinweise nicht erreichbar. Bitte neu öffnen.");}if(!r.ok)throw new Error(j.error||"Hinweise nicht erreichbar.");return j;
}
export function RadarSignals({scanVersion,reportTarget,onReportOpened,readOnly=false}:{scanVersion:number|null;reportTarget?:Store|null;onReportOpened?:()=>void;readOnly?:boolean}) {
  const [state,setState]=useState<Signals|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[shop,setShop]=useState("all");
  const [dialog,setDialog]=useState(false),[editing,setEditing]=useState<Observation|null>(null),[retailer,setRetailer]=useState("Hugendubel"),[kind,setKind]=useState<Observation["kind"]>("seen"),[source,setSource]=useState<Observation["source"]>("personal"),[precision,setPrecision]=useState<Observation["time_precision"]>("minute"),[other,setOther]=useState(false),[address,setAddress]=useState("");
  const reload=useCallback(()=>api().then(setState).catch(e=>setError(e.message)),[]);
  useEffect(()=>{void reload();},[reload,scanVersion]);
  useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void reload();},60000);return()=>clearInterval(timer);},[reload]);
  useEffect(()=>{if(!reportTarget||!state||readOnly)return;setEditing(null);setAddress(reportTarget.address);setRetailer(reportTarget.retailer);setKind("seen");setSource("personal");setPrecision("minute");setOther(false);setError("");setDialog(true);onReportOpened?.();},[reportTarget,state,onReportOpened,readOnly]);
  async function refresh(){if(readOnly){await reload();return;}setBusy(true);setError("");try{const data=await api({action:"refresh"});setState(data);setNotice(data.result?.checked?`${data.result.checked} öffentliche Feeds geprüft; ${data.result.imported} neue Prüfkandidaten.`:"Quellen sind noch im Prüfintervall. Nach einer Blockade: 30 Minuten Abstand.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function open(o:Observation|null=null,branch?:Signals["branches"][number]){if(readOnly){window.location.assign("/admin");return;}setEditing(o);setAddress(o?.address||branch?.address||"");setRetailer(o?.retailer||branch?.retailer||"Hugendubel");setKind(o?.kind||"seen");setSource(o?.source||"personal");setPrecision(o?.time_precision||"minute");setOther(false);setError("");setDialog(true);}
  async function save(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();if(readOnly)return;const f=new FormData(e.currentTarget);setBusy(true);setError("");
    const num=(k:string)=>f.get(k)?Number(String(f.get(k)).replace(",",".")):null;
    const report:ReportInput={retailer,address:String(f.get(other?"customAddress":"address")||"")||null,product:String(f.get("product")),kind,source,time_precision:precision,observed_at:new Date(String(f.get("observed"))+(precision==="day"?"T00:00:00":"")).getTime(),expected_at:kind==="announced"?new Date(String(f.get("expected"))).getTime():null,source_url:String(f.get("sourceUrl")||"")||null,note:String(f.get("note")||""),price:num("price"),uvp_price:num("uvpPrice"),uvp_source:String(f.get("uvpSource")||"")||null};
    try{setState(await api({action:"save",report,...(editing?{id:editing.id}:{})}));setDialog(false);setNotice("Beobachtung gespeichert.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  async function dismiss(id:string){if(readOnly)return;setBusy(true);try{setState(await api({action:"dismiss",id}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const branches=state?.branches.filter(b=>(shop==="all"||b.retailer===shop))||[];
  const actionable=branches.filter(b=>b.priority>0);
  const known=branches.filter(b=>b.priority<=0&&(b.observations.length>0||b.opening.state!=="unknown"));
  return <section className="signals-view">
    <div className="section-heading"><h2>Fahrtentscheidung heute</h2><button className="secondary" onClick={()=>open()}><Plus size={17}/>Fund eintragen</button></div>
    {error&&<div className="message error-message" role="alert"><AlertCircle size={18}/><span>{error}</span></div>}
    {notice&&<div className="message notice-message" role="status"><Check size={18}/><span>{notice}</span><button aria-label="Meldung schließen" onClick={()=>setNotice("")}><X size={16}/></button></div>}
    <div className="signal-filter"><label>Händler<select value={shop} onChange={e=>setShop(e.target.value)}><option value="all">Alle 10 Händler</option>{state?.retailers.map(r=><option key={r.name}>{r.name}</option>)}</select></label><span className="tiny">Stand {state?new Date(state.now).toLocaleTimeString("de-DE",{timeZone:"Europe/Berlin",hour:"2-digit",minute:"2-digit"}):"…"} · Berlin</span></div>
    {!state?<div className="empty-state"><RefreshCw className="spin"/><h3>Hinweise werden geladen</h3></div>:!actionable.length?<div className="signal-empty"><AlertCircle size={21}/><div><strong>Aktuell kein belastbarer Anlass zum Losfahren</strong><p>Kein frischer filialgenauer Fund und keine belegte heutige Lieferankündigung. Das bedeutet nicht, dass die Läden leer sind.</p></div></div>:<div className="signal-list">{actionable.map(b=><BranchSignal key={b.retailer+b.address} branch={b} onReport={()=>open(null,b)}/>)}</div>}
    {!!state?.unassigned.length&&<div className="signal-list"><h3>Filiale noch offen</h3>{state.unassigned.map(o=><ObservationRow key={o.id} observation={o} onEdit={()=>open(o)}/>)}</div>}
    {!!known.length&&<div className="signal-list"><h3>Weitere dokumentierte Filialen</h3>{known.map(b=><BranchSignal key={b.retailer+b.address} branch={b} onReport={()=>open(null,b)}/>)}</div>}
    {state&&<p className="tiny signal-coverage">{state.branches.length} Filialen im Verzeichnis · {state.branches.filter(b=>b.opening.state==="unknown").length} ohne geprüfte heutige Öffnungszeiten · {state.observations.filter(o=>o.reviewed===1).length} protokollierte Beobachtungen · keine kalibrierte Trefferquote</p>}
    {!!state?.candidates.length&&<div className="signal-list"><h3>Community-Meldungen zur Prüfung</h3>{state.candidates.map(o=><div key={o.id}><ObservationRow observation={o} onEdit={()=>open(o)}/><button className="secondary" disabled={busy} onClick={()=>void dismiss(o.id)}><X size={15}/>Unpassend</button></div>)}</div>}
    <div className="section-heading"><h2>Aktuelle öffentliche Berichte</h2><span className="tiny">Orte / Verfügbarkeit ungeprüft</span></div>
    <div className="research-list">{state?.posts.filter(p=>shop==="all"||p.retailers.includes(shop)).map(p=><article key={p.id}><div className="tiny">Zeit im Feed {new Date(p.published_at).toLocaleString("de-DE",{timeZone:"Europe/Berlin"})} · {p.retailers.join(", ")}</div><h3><a href={p.url} target="_blank" rel="noreferrer">{p.title}<ExternalLink size={14}/></a></h3><p>{p.excerpt}{p.excerpt.length===480?"…":""}</p><span className="tiny">Feed-Zeit, keine bestätigte Verräumzeit. Kein Leipziger Bestandsalarm.</span></article>)}</div>
    {state&&!state.posts.length&&<p className="tiny">Keine passenden Beiträge in den zuletzt lesbaren Feed-Antworten. Nicht sämtliche Gruppen oder Kommentare sind abgedeckt.</p>}
    <div className="section-heading source-heading"><h2>Öffentliche Community-Feeds</h2><button className="secondary" onClick={()=>void refresh()} disabled={busy}><RefreshCw size={16} className={busy?"spin":""}/>Prüfen</button></div>
    <div className="source-list">{state?.sources.map((s:any)=><div className="source-row" key={s.id}><div><strong>{s.name}</strong><span>{s.detail}</span><span>{s.checked_at?`Geprüft ${new Date(s.checked_at).toLocaleString("de-DE",{timeZone:"Europe/Berlin"})}`:"Noch kein erfolgreicher Abruf"}</span></div><span className={`badge ${s.status==="readable"?"neutral":"blocked"}`}>{s.status==="readable"?"Feed lesbar":s.status==="blocked"?"Nicht verbunden":"Ungeprüft"}</span><a className="icon-button" title="Original im Browser öffnen" aria-label={`${s.name}: Original öffnen`} href={s.url} target="_blank" rel="noreferrer"><ExternalLink size={17}/></a></div>)}</div>
    <p className="tiny signal-coverage">Browser-Sicherheitschecks sind sitzungsgebunden. Ein gelöster Check gibt den Serverabruf nicht automatisch frei. Private Messenger- und Facebook-Gruppen sind nicht verbunden.</p>
    <div className="section-heading"><h2>Recherchebelege</h2><span className="tiny">Keine heutigen Bestandsmeldungen</span></div>
    <div className="research-list">{state?.research.map(r=><article key={r.id}><div className="tiny">{r.date} · {r.scope}</div><h3><a href={r.url} target="_blank" rel="noreferrer">{r.title}<ExternalLink size={14}/></a></h3><p>{r.summary}</p></article>)}</div>
    <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="product-dialog"><DialogHeader><DialogTitle>{editing?"Beobachtung prüfen / ergänzen":"Vor-Ort-Beobachtung"}</DialogTitle><DialogDescription>Pokémon 30 Jahre · keine Versandangebote</DialogDescription></DialogHeader><form className="product-form signal-form" onSubmit={save} key={editing?.id||"new"}>
      <label>Händler<select value={retailer} onChange={e=>{setRetailer(e.target.value);setAddress("");}}>{state?.retailers.map(r=><option key={r.name}>{r.name}</option>)}</select></label>
      <label>Filiale<select name="address" value={address} onChange={e=>setAddress(e.target.value)} disabled={other}><option value="">Zuordnung offen</option>{state?.branches.filter(b=>b.retailer===retailer).map(b=><option key={b.address} value={b.address}>{b.name} · {b.address}</option>)}</select></label>
      <label className="inline-check"><input type="checkbox" checked={other} onChange={e=>setOther(e.target.checked)}/>Weitere Filialadresse</label>{other&&<label>Genaue Adresse<input name="customAddress" required maxLength={200} placeholder="Straße, Hausnummer, PLZ Leipzig"/></label>}
      <label>Artikel<input name="product" required minLength={3} maxLength={180} defaultValue={editing?.product||"Pokémon 30 Jahre Boosterbundle"}/></label>
      <div className="form-pair"><label>Beobachtung<select value={kind} onChange={e=>setKind(e.target.value as Observation["kind"])}>{Object.entries(kindNames).map(([k,n])=><option value={k} key={k}>{n}</option>)}</select></label><label>Quelle<select value={source} onChange={e=>setSource(e.target.value as Observation["source"])}>{Object.entries(sourceNames).map(([k,n])=><option value={k} key={k}>{n}</option>)}</select></label></div>
      <label className="inline-check"><input type="checkbox" checked={precision==="day"} onChange={e=>setPrecision(e.target.checked?"day":"minute")}/>Uhrzeit unbekannt</label>
      <label>Beobachtet ({Intl.DateTimeFormat().resolvedOptions().timeZone})<input key={precision} name="observed" type={precision==="day"?"date":"datetime-local"} required defaultValue={localInput(editing?.observed_at||Date.now()).slice(0,precision==="day"?10:16)}/></label>
      {kind==="announced"&&<label>Angekündigt für<input name="expected" type="datetime-local" required defaultValue={editing?.expected_at?localInput(editing.expected_at):""}/></label>}
      <label>Original-Beleglink<input name="sourceUrl" type="url" required={source==="community"} maxLength={2000} defaultValue={editing?.source_url||""}/></label>
      <div className="form-pair"><label>Filialpreis (EUR)<input name="price" type="number" min="0.01" max="10000" step="0.01" defaultValue={editing?.price??""}/></label><label>UVP-Referenz (EUR)<input name="uvpPrice" type="number" min="0.01" max="10000" step="0.01" defaultValue={editing?.uvp_price??""}/></label></div>
      <label>UVP-Beleg genau dieses Artikels<input name="uvpSource" type="url" maxLength={2000} defaultValue={editing?.uvp_source||""}/></label>
      <label>Notiz<textarea name="note" rows={3} maxLength={1000} defaultValue={editing?.note||""}/></label>
      <p className="tiny">Fundmeldungs-Push nur bei frischer, geprüfter Filialzuordnung mit Filialpreis im belegten UVP-Rahmen. Historische Beobachtungen und Gerüchte lösen keinen Alarm aus.</p>
      {error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" type="submit" disabled={busy}><Check size={17}/>Beobachtung speichern</button>
    </form></DialogContent></Dialog>
  </section>;
}
function ObservationRow({observation:o,onEdit}:{observation:Observation;onEdit:()=>void}){return <article className="observation-row"><div><span className="tiny">{date(o)} · {sourceNames[o.source]} · {o.reviewed===0?"Ungeprüft":Date.now()-o.observed_at>20*60000?"Historisch / nicht frisch":"Zeitnah gemeldet"}</span><strong>{o.retailer}: {o.product}</strong><span>{kindNames[o.kind]} · {o.address||"Filialzuordnung offen"}</span><p>{o.note}</p><span className="tiny">{o.price===null?"Preis offen":`${o.price.toFixed(2)} EUR`} · {o.uvp_price===null?"UVP-Referenz offen":`Referenz ${o.uvp_price.toFixed(2)} EUR`}</span></div><div className="observation-actions">{o.source_url&&<a className="icon-button" href={o.source_url} target="_blank" rel="noreferrer" title="Original-Beleg" aria-label="Original-Beleg"><ExternalLink size={16}/></a>}<button className="icon-button" title="Beobachtung ergänzen" aria-label={`${o.retailer}: Beobachtung ergänzen`} onClick={onEdit}><Pencil size={16}/></button></div></article>;}
function BranchSignal({branch:b,onReport}:{branch:Signals["branches"][number];onReport:()=>void}){return <article className="branch-signal"><div><div className="product-retailer">{b.retailer}</div><h3>{b.name}</h3><p>{b.address}</p><span className={`badge ${b.priority>=4?"available":b.priority>0?"unknown":"neutral"}`}>{b.label}</span><p>{b.reason}</p><div className="signal-evidence"><span><Clock size={14}/>{b.opening.label}</span>{b.visits>0&&<span>{b.found} positive von {b.visits} eigenen dokumentierten Besuchstagen</span>}{b.windows.map(w=><span key={w.start}>Historisches Fenster {clock(w.start)}–{clock(w.end)} · {w.days} Beobachtungstage</span>)}</div>{b.observations[0]&&<p className="tiny">Letzte Beobachtung: {date(b.observations[0])} · {sourceNames[b.observations[0].source]}</p>}</div><div className="signal-actions"><a className="icon-button" href={`https://maps.apple.com/?daddr=${encodeURIComponent(b.address)}`} target="_blank" rel="noreferrer" title="Route" aria-label={`${b.name}: Route`}><Navigation size={17}/></a><a className="icon-button" href={b.url} target="_blank" rel="noreferrer" title="Filialseite" aria-label={`${b.name}: Filialseite`}><ExternalLink size={17}/></a><button className="icon-button" title="Fund melden" aria-label={`${b.name}: Fund melden`} onClick={onReport}><MapPin size={17}/></button></div></article>;}
