import type { Hours, Observation } from "./intelligence.ts";

export const researchNotes = [
  {id:"record-deliveries",title:"Liefertage und Verräumzeiten werden protokolliert",scope:"Deutschland · keine Leipziger Filialzusage",url:"https://www.reddit.com/r/PokemonTCG_DE/comments/1wpuchy/frustration_30_jahre_jubil%C3%A4um/",date:"25.09.2026",summary:"Ein Sammler beschreibt mehrere Wochen eigener Notizen zu Liefertagen und Verräumzeiten einzelner Filialen. Andere Kommentare berichten von Gruppenmeldungen und kurzfristig verschobenen Lieferungen. Erfahrungsberichte, keine geprüften Lieferpläne."},
  {id:"times-vary",title:"Nachlegen ist nicht auf die Ladenöffnung begrenzt",scope:"Deutschland · Filiale ungenannt",url:"https://www.reddit.com/r/PokemonTCG_DE/comments/1tig0d5/wie_wisst_ihr_wann_restocks_in_l%C3%A4den_kommen/",date:"20.–21.05.2026",summary:"Berichte nennen bekannte Liefertage, kurzfristige WhatsApp-/Reddit-Hinweise und einen Müller mit Auffüllen nach 14 Uhr. Ein anderer Händler beschreibt unregelmäßige Zuteilungen. Daraus folgt kein allgemeiner Liefertag für Müller oder Leipzig."},
  {id:"short-lived",title:"Berichte über kurze Verkaufsfenster",scope:"Deutschland · regional unterschiedlich",url:"https://www.reddit.com/r/PokemonTCG_DE/comments/1wu2jb7/2_wochen_nach_release_habt_ihr_irgendwo_etwas/",date:"30.09.2026",summary:"Einzelne Community-Berichte nennen Nachschub vormittags oder nachmittags und Ausverkauf innerhalb von 30–60 Minuten, teils schneller. Nicht unabhängig verifiziert. Deshalb werden alte Funde nicht als aktueller Bestand angezeigt."},
  {id:"leipzig-release",title:"Leipziger Meldungen zum Erstverkauf",scope:"Leipzig · historisch, nicht heute",url:"https://www.reddit.com/r/PokemonTCG_DE/comments/1whedhi/sammelthread_30th_release/",date:"16.09.2026",summary:"Kommentare berichten zum Erstverkauf von fehlender Ware bei Leipziger MediaMarkt-, Hugendubel- und Müller-Läden. Konkrete Filialen fehlen. Das ist ausdrücklich keine Aussage über den heutigen Bestand."},
  {id:"live-inventory-tools",title:"Filialabfragen und Gruppeninfos sind getrennte Quellen",scope:"Anbieterbeschreibung · Zugriff nicht verifiziert",url:"https://www.teamrestocks.de/",date:"Recherche 06.10.2026",summary:"Team Restocks bewirbt Live-Filialabfragen für Rossmann, HIT und budni sowie zusätzliche In-Store-Informationen und Reddit-/MyDealz-Feeds. Zugang ist kostenpflichtig; die beworbene Funktion wurde hier nicht unabhängig getestet. Kein Beleg für einen Thalia-Warenwirtschaftszugang."},
  {id:"local-group",title:"Leipzig/Halle: lokale Messengergruppe erwähnt",scope:"Leipzig/Halle · Zugang und Restock-Inhalte offen",url:"https://www.reddit.com/r/Leipzig/comments/1tya3q3/pokemon_tcg_messengergruppen_in_leipzig/",date:"06.06.2026",summary:"Ein Leipziger Beitrag fragt nach unabhängigen Gruppen. Eine Antwort nennt eine Leipzig/Halle-Gruppe und QR-Codes bei lokalen Treffen. Belegt ist die öffentliche Erwähnung, nicht deren heutige Aktivität oder eine Restock-Abdeckung der zehn Händler."},
  {id:"smyths-provider",title:"Smyths-DE-Filialmonitor als Anschlusskandidat",scope:"Anbieterbeispiele · kein aktiver Radar-Zugang",url:"https://tcg-alerts.com/de",date:"Recherche 06.10.2026",summary:"TCG Alerts zeigt Smyths-DE-Beispiele mit Produkt, Filiale und Stückzahl. Die gezeigten Preise sind N/A; sie belegen weder UVP noch einen heutigen Leipziger Drop. Monitorzugang wird im Premiumplan für 4,99 EUR/Monat beworben. Abdeckung, Aktualität und Importrechte sind nicht unabhängig verifiziert."},
];
const checkedAt=Date.parse("2026-10-06T09:00:00+02:00");
const weekdays=(start:number,end:number)=>Object.fromEntries(["Mon","Tue","Wed","Thu","Fri"].map(day=>[day,[[start,end]]])) as Record<string,[number,number][]>;
export const knownHours:Hours[]=[
  {retailer:"Thalia",address:"Karl-Liebknecht-Str. 8–14, 04107 Leipzig",weekly:{...weekdays(540,1110),Sat:[[540,900]],Sun:[]},exceptions:{"2026-10-03":[],"2026-10-31":[],"2026-11-18":[],"2026-11-28":[[540,960]],"2026-12-05":[[540,960]],"2026-12-12":[[540,960]],"2026-12-19":[[540,960]],"2026-12-24":[[540,780]],"2026-12-25":[],"2026-12-26":[],"2026-12-31":[[540,780]],"2027-01-01":[]},source_url:"https://www.thalia.de/buchhandlung/5629",checked_at:Date.parse("2026-10-06T20:56:00+02:00")},
  {retailer:"Hugendubel",address:"Petersstraße 12–14, 04109 Leipzig",weekly:{...weekdays(600,1200),Sat:[[600,1200]],Sun:[]},exceptions:{},source_url:"https://www.hugendubel.de/de/branch?branchId=9816",checked_at:checkedAt},
  {retailer:"GALERIA",address:"Neumarkt 1, 04109 Leipzig",weekly:{...weekdays(600,1200),Sat:[[600,1200]],Sun:[]},exceptions:{},source_url:"https://www.galeria.de/filialen/l/leipzig/neumarkt-1/001559",checked_at:checkedAt},
  {retailer:"Rossmann",address:"Petersstraße 44, 04109 Leipzig",weekly:{...weekdays(540,1200),Sun:[]},exceptions:{"2026-10-03":[]},source_url:"https://www.rossmann.de/de/filialen/sachsen/leipzig/petersstr--44.html",checked_at:checkedAt},
  {retailer:"REWE",address:"Willy-Brandt-Platz 4, 04103 Leipzig",weekly:{...weekdays(480,1320),Sat:[[480,1320]],Sun:[[720,1080]]},exceptions:{"2026-10-31":[[480,1320]]},source_url:"https://www.rewe.de/marktseite/leipzig/4040174/rewe-markt-willy-brandt-platz-4/",checked_at:Date.parse("2026-10-06T20:56:00+02:00")},
];
export const initialObservations:Omit<Observation,"created_at">[]=[
  {id:"user-hugendubel-2026-10-05",retailer:"Hugendubel",address:null,product:"Pokémon 30 Jahre Boosterbundle",kind:"restock",source:"personal",time_precision:"minute",observed_at:Date.parse("2026-10-05T12:20:00+02:00"),expected_at:null,source_url:null,note:"Eigener Fund: Ware wurde gegen 12:20 einsortiert, ein Boosterbundle gekauft. Genaue Filiale und Preis noch offen.",price:null,uvp_price:null,uvp_source:null,reviewed:1,push_state:"historical"},
  {id:"user-thalia-2026-10-05",retailer:"Thalia",address:"Karl-Liebknecht-Str. 8–14, 04107 Leipzig",product:"Pokémon 30 Jahre Kartenware",kind:"seen",source:"secondhand",time_precision:"day",observed_at:Date.parse("2026-10-05T00:00:00+02:00"),expected_at:null,source_url:null,note:"Du hast einen Bestands-/Restock-Hinweis in der App eines anderen Sammlers gesehen. Uhrzeit, Artikel und Preis unbekannt. Kein unabhängig überprüfter Filialbestand.",price:null,uvp_price:null,uvp_source:null,reviewed:1,push_state:"historical"},
];
